### ISSUE TITLE
Separate Devnet and Mainnet

### ISSUE THREAD

**Issue by peterwht** [paritytech/extended-parachain-template#10]
Most parachains will have separate runtimes for Devnet and Mainnet. This template should come prebuilt with this separation to reduce friction for new parachain teams.

- [x] Create new runtime folder `devnet`
    - [x] Set spec_name for devnet
    - [x] set impl_name for devnet
    - [x] set Cargo.toml name for devnet
- [x] Create new runtime folder `mainnet`
    - [x] Set spec_name for mainnet
    - [x] set impl_name for mainnet
    - [x] set Cargo.toml name for mainnet
- [x] Create new runtime folder `common`
- [x] Update command.rs and chain_spec.rs to include devnet and mainnet
- [x] Add `RuntimeResolver` to client to choose between devnet and mainnet
        - https://github.com/Watr-Protocol/watr/commit/b285217c41a5a6deb291f57629230746c3fa5bcd
        - https://github.com/Watr-Protocol/watr/commit/ce315607c3d923d62523994e4cce7a58b1c0c8eb

**Comment by stiiifff** [comment]
Closed by  #44
