### ISSUE TITLE
Improve Github Actions 

### ISSUE THREAD

**Issue by weezy20** [paritytech/extended-parachain-template#35]
Problem: We are running out of disk space by the time the GH actions reaches the `Ensure Benchmarking Compiles` step. This is annoying as we have limited disk space and running each step without caching build artifacts can take up too much time.

PR #34

**Comment by stiiifff** [comment]
@weezy20 Is this closed by #34

**Comment by weezy20** [comment]
@stiiifff As mentioned in the #34, while this does make the CI pass, it's not the best solution considering that we don't make use of caching. I'd prefer to keep this issue open while we investigate how to introduce caching of dependencies.
