### ISSUE TITLE
cannot find macro `vec` in this scope and mismatched types

### ISSUE THREAD

**Issue by ganesh1233456** [paritytech/extended-parachain-template#65]
I am just now upgrading my chain to `polkadot-v1.0.0` where I am using [extend-parachain-template](https://github.com/ganesh1233456/xcav-parachain/tree/fixing-staking-pallet-issue) but I got this issue while build. Someone please give some advice why I am getting this.

```
error: cannot find macro `vec` in this scope
   --> /Users/ganesholi/.cargo/git/checkouts/substrate-7e08433d4c370a21/ff24c60/frame/assets/src/functions.rs:702:46
    |
702 |         let mut dead_accounts: Vec<T::AccountId> = vec![];
    |                                                    ^^^
    |
help: consider importing one of these items
    |
20  + use codec::alloc::vec;
    |
20  + use scale_info::prelude::vec;
    |
20  + use sp_std::vec;
    |

error[E0308]: mismatched types
   --> /Users/ganesholi/.cargo/git/checkouts/substrate-7e08433d4c370a21/ff24c60/frame/assets/src/functions.rs:713:32
    |
32  | impl<T: Config<I>, I: 'static> Pallet<T, I> {
    |      - this type parameter
...
713 |                     if dead_accounts.len() >= (max_items as usize) {
    |                                               ^^^^^^^^^^^^^^^^^^^^ expected type parameter `T`, found `usize`
    |
    = note: expected type parameter `T`
                         found type `usize`

   Compiling frame-support v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v1.0.0#ff24c60a)
   Compiling sp-consensus v0.10.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v1.0.0#ff24c60a)
For more information about this error, try `rustc --explain E0308`.
error: could not compile `pallet-assets` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
ganesholi@Ganeshs-MacBook-Air xcav-parachain % 
```

**Comment by weezy20** [comment]
`EPT` is already on polkadot-v1.0 so you shouldn't be required to manually update it. For the `vec` you can apply the suggestions mentioned in the error message, such as importing `sp_std::vec` and make sure you also enable `std` features of your dependencies under the `std` feature of your pallet to prevent weird compilation issues.

**Comment by ganesh1233456** [comment]
> `EPT` is already on polkadot-v1.0 so you shouldn't be required to manually update it. For the `vec` you can apply the suggestions mentioned in the error message, such as importing `sp_std::vec` and make sure you also enable `std` features of your dependencies under the `std` feature of your pallet to prevent weird compilation issues.

I was using `EPT` since `polkadot-v0.9.42` so you've updated 2 weeks ago to `1.0.0` that's why I am updating to latest one manually. Is doing so wrong? and about `vec` it says to add `use codec::alloc::vec;` but where I don't understand because `pallet-asset` is substrate frame dependencies and how to update it?

**Comment by weezy20** [comment]
@ganesh1233456 Of course you're free to do the update however you please, but take care of the dependency feature flags. Most likely you missed out `pallet-assets/std` under `[std]` feature somewhere.
