### ISSUE TITLE
Unable to export genesis state to the local Relay chain

### ISSUE THREAD

**Issue by Retamogordo** [paritytech/extended-parachain-template#70]
Hi, 
I follow the instructions from
https://docs.substrate.io/tutorials/build-a-parachain/connect-a-local-parachain/
in order to register a freshly forked ```extended-parachain-template``` on a locally running Relay chain.
I get the following printout upon trying to register the parachain on the local relay chain:
```
./target/release/parachain-template-node export-genesis-state --chain raw-parachain-chainspec.json para-2000-genesis-state
2023-09-10 09:33:24 Essential task `transaction-pool-task-1` failed. Shutting down service.    
2023-09-10 09:33:24 Essential task `basic-block-import-worker` failed. Shutting down service.    
2023-09-10 09:33:24 Essential task `transaction-pool-task-0` failed. Shutting down service.    
2023-09-10 09:33:24 Essential task `txpool-background` failed. Shutting down service.
```
The relay chain runs with a fresh db starting from block 0.
I conducted the same procedure with a ```substrate-parachain-template``` and haven't faced the issue.
After trying a few times I see, that it's 100% reproducible on my machine.
Here is the snippet of the chainspec json file for the ```extended-parachain-template```:
```
{
  "name": "Development Local Testnet",
  "id": "dev_local_testnet",
  "chainType": "Local",
  "bootNodes": [],
  "telemetryEndpoints": null,
  "protocolId": "template-local",
  "properties": {
    "ss58Format": 42,
    "tokenDecimals": 12,
    "tokenSymbol": "UNIT"
  },
  "relay_chain": "rococo-local",
  "para_id": 2000,
  "codeSubstitutes": {},
...
```
The chainspec of the ```substrate-parachain-template``` that registers successfully looks similar:
```
{
  "name": "Local Testnet",
  "id": "local_testnet",
  "chainType": "Local",
  "bootNodes": [],
  "telemetryEndpoints": null,
  "protocolId": "template-local",
  "properties": {
    "ss58Format": 42,
    "tokenDecimals": 12,
    "tokenSymbol": "UNIT"
  },
  "relay_chain": "rococo-local",
  "para_id": 2000,
  "codeSubstitutes": {},
  "genesis": {
    "runtime": {
...
```
I have attached both full plain chainspec files.

[plain-parachain-template-chainspec.txt](https://github.com/paritytech/extended-parachain-template/files/12568241/plain-parachain-chainspec.txt)
[plain-extended-parachain-template-chainspec.txt](https://github.com/paritytech/extended-parachain-template/files/12568246/plain-parachain-chainspec.txt)

**Comment by ganesh1233456** [comment]
I am also facing same issue while exporting genesis state

**Comment by stiiifff** [comment]
@Retamogordo @ganesh1233456 Thanks for reporting this, we will address it asap.
