### ISSUE TITLE
Safe Mode capability

### ISSUE THREAD

**Issue by stiiifff** [paritytech/extended-parachain-template#72]
Having the ability to temporarily pause transfers & normal operations on a live parachain is a valuable mechanism, when an issue / attack occurs. This is especially useful during the launch period of a parachain whereby the runtime code might not always have been battle-tested yet. Past this initial period, the chain’s Governance body (or Sudo account(s)) could decide to remove this capability to fully decentralize the network. The Substrate FRAME library contains the [SafeMode & TxPause pallets](https://github.com/paritytech/substrate/pull/12092) which allow to implement such a mechanism.

- [ ] Integrate the FRAME SafeMode & TxPause pallets with sane defaults in both devnet & mainnet runtimes (disabled by default in both runtimes).
- [ ] SafeMode should only allow balance transfers as whitelisted call. Permissionless operations (enter, extend) should be disabled. Only a privileged origin can enable / disable safe mode: `ForceEnterOrigin`, `ForceExtendOrigin` & `ForceExitOrigin` to be configured as the Root origin (Sudo).
- [ ] TxPause `PauseOrigin` & `UnpauseOrigin` to be configured as the Root origin (Sudo).

Depends on #71

**Comment by Daanvdplas** [comment]
I would like to take this one :)

**Comment by Moliholy** [comment]
@Daanvdplas Do you still want to pick up this issue?  I just completed the equivalent issue for Trappist, so I thought to complete it here.

**Comment by Daanvdplas** [comment]
Go for it!
