### ISSUE TITLE
[CI] Include build badge in README

### ISSUE THREAD

**Issue by stiiifff** [paritytech/extended-parachain-template#73]
Include a build badge in the project’s README to show the build status of the latest PR / commit that was merged into the project’s main branch.

**Comment by Moliholy** [comment]
@stiiifff this can potentially be misleading. If users were to fork this project they'd see the badge of the original repository (this one) instead of their fork. In a normal repository that is not meant to be forked this is not a problem, but in this case it might be. Should we still do it?
