### ISSUE TITLE
[QA] Example Parachain Integration tests

### ISSUE THREAD

**Issue by stiiifff** [paritytech/extended-parachain-template#77]
Implement some example integration tests using the [parachains-integration-tests tool](https://github.com/paritytech/parachains-integration-tests) (see [example in Trappist](https://github.com/paritytech/trappist/tree/main/integration-tests)), amend the repository structure as needed, and add a documentation page explaining how to configure and run the tests locally.

**Comment by AlexD10S** [comment]
I used this tool for the last Learning Session about XCM testing. Happy to take this one
